### ISSUE TITLE
Duvida: funciona com a easyinvest?

### ISSUE THREAD

**Issue by guilhermecgs** [barbolo/ir_investidor#1]

**Comment by barbolo** [comment]
@guilhermecgs Estou fazendo algumas alterações. Eu recomendo acompanhar a branch https://github.com/barbolo/ir_investidor/tree/new

Respondendo à sua pergunta. Não funciona integrado com nenhuma corretora. Foi uma ideia inicial para o projeto, mas eu desistir. Estou focando o projeto agora em um sistema que faz bem apenas o cálculo de impostos e não a gestão de recursos em corretoras.

**Comment by guilhermecgs** [comment]
@barbolo , acho que vou comecar a utilizar...
Vc acha que esta maduro o projeto? 

Na pagina inicial fala que nao funciona com FII, mas eu estou imaginando que o IR de FII eh a mesma coisa de IR de acao, nao?

**Comment by barbolo** [comment]
Oi @guilhermecgs.

A branch `new` funciona com FIIs sim.
Eu tenho usado direto e está tudo ok. Me avisa se tiver algum problema.
Você precisa colocar suas operações em uma planilha como esta: http://bit.ly/irinvestidor-planilha
Daí abre o IR Investidor e faz upload da planilha. O sistema deve calcular automaticamente as posições e o DARF.

Quando estiver finalizado, você vai abrir uma URL parecida com esta:
http://localhost:3060/posicoes/738d34f92447aec39cf6899521abbce8fe23ed328e344b3b3e0e94e7a4d6d2b9

Se os workers de cálculos não funcionarem corretamente, você pode abrir um console Ruby e rodar isso aqui:

```ruby
def run
  (reload!
  Order.destroy_all; SessionLog.destroy_all; TaxEntry.destroy_all; Tax.destroy_all; Asset.destroy_all;
  SheetParseWorker.new.perform(Session.last.id)
  Sidekiq::Queue.new('order_create').each { |job| OrderCreateWorker.new.perform job.args[0] }
  Sidekiq::Queue.new('order_create').clear
  (calculator = AssetCalculator.new(Session.last)).calculate_and_save
  nil)
end
run
```

**Comment by guilhermecgs** [comment]
ok cara!  valeu!

isso eh uma mina de dinheiro..  coloca um site 100% funcional e vende com propaganda que vc vai ganhar dinheiro

**Comment by barbolo** [comment]
Subi uma nova versão que eu vinha usando há alguns meses. Dá uma olhada no README atualizado do projeto. Tem um exemplo de script para converter nota de corretagem para excel.
