### ISSUE TITLE
Erro na conversão PDF/planilha executavel no programa. 

### ISSUE THREAD

**Issue by qwertytestenow** [barbolo/ir_investidor#11]
alguma sugestão: ? ->   
####
1: from scripts/clear.rb:3:in `<main>'
scripts/clear.rb:3:in `require': cannot load such file -- posix/spawn (LoadError) 
####

**Comment by barbolo** [comment]
Olá. Acabei de enviar diversas mudanças para o repositório.

Poderia atualizar seu repositório e tentar rodar novamente?

Removi a dependência da gem `posix/spawn` que impedia a execução do script da clear em ambiente Windows.

**Comment by qwertytestenow** [comment]
opa barbolo, então, meu problema aqui é no macbook, vou tentar te passo um feedback. obg

**Comment by qwertytestenow** [comment]
ops. seguir o feekback que me passou, jaja te falo. obg

**Comment by barbolo** [comment]
Imagino que tenha dado certo. Vou fechar a issue.

**Comment by qwertytestenow** [comment]
Opa, pois diga barbolo, acabei enviando aqui o erro só que parece que não enviou, então, vou te encaminhar novamente aqui :
