### ISSUE TITLE
Help na conversão do PDF/ agora require axlsx; 

### ISSUE THREAD

**Issue by qwertytestenow** [barbolo/ir_investidor#12]
Opa, boa tarde barbolo, tudo bem, irmão aquele aparentemente passou, queria ver contigo esse aqui se possível: 

######
1: from scripts/clear.rb:4:in `<main>'
scripts/clear.rb:4:in `require': cannot load such file -- axlsx 
#####

execução completa: 
#####
Starting ir_investidor_redis_1 ... done
Starting ir_investidor_db_1    ... done
Traceback (most recent call last):
	1: from scripts/clear.rb:4:in `<main>'
scripts/clear.rb:4:in `require': cannot load such file -- axlsx (LoadError)
#######

desde já agradeço. obrigado.

**Comment by barbolo** [comment]
Roda isso aqui para instalar as gems (bibliotecas de Ruby necessárias):

```gem install nokogiri axlsx```

E também isso aqui para instalar o `pdftohtml`:

```
# mac
brew install poppler

# ubuntu
sudo apt-get install poppler-utils
```
