### ISSUE TITLE
Dificuldades de se utilizar o conversor

### ISSUE THREAD

**Issue by brunohop** [barbolo/ir_investidor#16]
Olá amigo.
Não sou muito experiente em ruby, fiz só um projeto para uso pessoal. Então me desculpe se a dúvida for meio básica.
(Já olhei as outras issues fechadas)
Notei que no conversor vc usa as gem 'nokogiri',  'axlsx', 'csv'. Tentei instalá-las separadamente, mas da erro. Tentei adicionar no gemfile e vi que da um erro de versão da dependência rubyzip entre a gem axlsx e a roo.
Fui instalar o brew no docker e tb tive problemas com a versão do ruby. Apesar do erro, parece ser dispensável essa instalação, pois consegui instalar o poppler. Enfim, estou apanhando cada vez mais.
Só quero perguntar se o código do conversor está essa questão das Gems. O que está no gemfile basta, ou tenho que instalar manualmente as três?
Parabéns pelo projeto. Já fiz o fork! espero conseguir contribuir

**Comment by barbolo** [comment]
Oi @brunohop.

O conversor é um script independente do resto do projeto (pode ignorar o `Gemfile` do projeto):
https://github.com/barbolo/ir_investidor/blob/master/scripts/clear.rb

Existem 3 dependências para o script poder executar:
- `poppler` (deve ser instalado no seu sistema operacional, veja opções de instalação em https://poppler.freedesktop.org/)
- `nokogiri` (`gem install nokogiri`)
- `axlsx` (`gem install axlsx`)

Você pode validar a instalação do `poppler` com o comando abaixo:

`pdftohtml -stdout -xml -i arquivo.pdf`

A saída esperada desse comando é um XML com o conteúdo do PDF.

Qualquer versão recente do `nokogiri` ou do `axlsx` deve ser suficiente para o script funcionar. Ele não usa nada muito específico dessas gems.
