### ISSUE TITLE
/usr/local/lib/ruby/2.5.0/csv.rb:2046:in `=~': invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by gabricar** [barbolo/ir_investidor#24]
Tentando importar um PDF da XP e recebo esse error. Alguma idea?

 docker-compose run web bundle exec ruby scripts/clear.rb ~/Downloads/notas
Creating ir_investidor_web_run ... done
Processando PDFs do diretório: ~/Downloads/notas
Traceback (most recent call last):
	6: from scripts/clear.rb:23:in `<main>'
	5: from /usr/local/lib/ruby/2.5.0/csv.rb:1346:in `read'
	4: from /usr/local/lib/ruby/2.5.0/csv.rb:1280:in `open'
	3: from /usr/local/lib/ruby/2.5.0/csv.rb:1280:in `new'
	2: from /usr/local/lib/ruby/2.5.0/csv.rb:1552:in `initialize'
	1: from /usr/local/lib/ruby/2.5.0/csv.rb:2046:in `init_separators'
/usr/local/lib/ruby/2.5.0/csv.rb:2046:in `=~': invalid byte sequence in US-ASCII (ArgumentError)
ERROR: 1

**Comment by barbolo** [comment]
Foi feito para a Clear. Não tenho ideia se deveria funcionar na nota da XP.

**Comment by gabricar** [comment]
Obrigado pela resposta. O trabalho de voces esta show de bola! Pena que nao tenho tempo de criar a planilha na mao.
